### ISSUE TITLE
Image not be displayed

### ISSUE THREAD

**Issue by kemalbalaban** [guillermomartinez/filemanager-laravel#1]
Hi,

I checked the correct image directory, but can not be displayed.
http://prntscr.com/5rw3v1

**Comment by guillermomartinez** [comment]
Hello, it may be because the permissions on the folder laravel\public\filemanager\userfiles
test: 
chmod -R 777 laravel\public\filemanager\userfiles
recommended:
chmod -R 755 laravel\public\filemanager\userfiles

**Comment by tudor2004** [comment]
Hi,
I had a similar problem but it wasn't a permission issue. My app was running perfectly on local server (homestead and also using MAMP). The issue appeared only after deploying to heroku. I removed the line  php_flag engine off from the .htaccess file (public/filemanager/userfiles) and than it worked again.  More infos here - [StackOverflow](http://stackoverflow.com/questions/23457429/my-heroku-static-site-broke-with-the-new-php-system)

**Comment by guillermomartinez** [comment]
For security engine must be off in userfiles folder
`php_flag engine off`
[Config PHP ini.engine](http://php.net/manual/en/apache.configuration.php#ini.engine)
