### ISSUE TITLE
Problem path

### ISSUE THREAD

**Issue by hunterbit** [guillermomartinez/filemanager-laravel#10]
Hello,
I have installed the project, but I have problems with paths. I use the extension to my admin panel and the route is under admin / filemanager.

When I installed the file manager my route is admin / filemanager but the route of the project file manager.

How can I change this?

**Comment by guillermomartinez** [comment]
Tal vez te refieres a este problema que ya fue resuelto en la versión [2.0.1](https://github.com/guillermomartinez/filemanager-laravel/commit/b290534fe02c30f305dfc83318669c81a095e4df)
