### ISSUE TITLE
Not Found FileManager!!

### ISSUE THREAD

**Issue by Gantulga15** [guillermomartinez/filemanager-laravel#11]
![problen](https://cloud.githubusercontent.com/assets/4876769/7666999/f7f41738-fc2c-11e4-9772-2c06cec755f7.JPG)

**Comment by guillermomartinez** [comment]
Por defecto funciona si tu url es http://localhost/ , si es otra url debes cambiar en [/tinymce/tinymce_editor.js](https://github.com/guillermomartinez/filemanager-laravel/blob/master/public/tinymce/tinymce_editor.js#L31)

**Comment by Gantulga15** [comment]
sorry. I'm beginner the laravel. I can't fix the problem. These error pics.
![1](https://cloud.githubusercontent.com/assets/4876769/7677642/6d568282-fd80-11e4-9169-256e3841e3ff.jpg)
![rout](https://cloud.githubusercontent.com/assets/4876769/7677643/6d8bd3ba-fd80-11e4-9134-9e0189c6d0bf.JPG)
![tiny](https://cloud.githubusercontent.com/assets/4876769/7677644/6dbdf1ec-fd80-11e4-8482-f2aa273f4c52.JPG)

**Comment by guillermomartinez** [comment]
Prueba con la versión [2.0.1](https://github.com/guillermomartinez/filemanager-laravel/commit/b290534fe02c30f305dfc83318669c81a095e4df)

`composer update`
`php artisan vendor:publish`

y en FilemanagerLaravelController.php modifica con tu patch
`$f->connector_url = url('/').'/admin/filemanager/connectors';`
