### ISSUE TITLE
No está mostrando filemannager

### ISSUE THREAD

**Issue by Punksolid** [guillermomartinez/filemanager-laravel#15]
Hola Guillermo
Cuando coloco el codigo me carga el tinymce con todo y los botones de filemannager, solo que cuando doy clic no carga nada en el body del filemannager y también no es la intención de que cargue todo el wysiwyg.

No encontré como configurar esa parte.

Gracias

**Comment by guillermomartinez** [comment]
Si solo quieres que carge el filemanager sin usar el tinymce, entonces entra a la ruta http://dominio.com/filemanager/show

**Comment by Punksolid** [comment]
Funcionó, gracias
