### ISSUE TITLE
Error POST  http:......../filemanager/connectors 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Punksolid** [guillermomartinez/filemanager-laravel#16]
Creo que tengo un problema con los conectors, marca error al subir archivo. no sé donde especificar el conector php, o si ya viene incluido dentro de los vendors.

Saludos.

**Comment by guillermomartinez** [comment]
Reviza https://github.com/guillermomartinez/filemanager-laravel/issues/11

**Comment by Punksolid** [comment]
Ya habia revisado, el problema fue otro, que mi usuario PHP no permite hacer chmod, entonces retornaba un error. Ahora ya el ultimo problema es que no me devuelve los thumnails, me devuelve un error 404. 

Tengo cuatro imagenes las cuales me devuelve error, pero las imagenes si están en las rutas. 
![2015-06-15 15_31_12-developer tools - http___10 0 0 21_laccion_public_xdit_products_product_add](https://cloud.githubusercontent.com/assets/416409/8167359/2a7a2d88-1374-11e5-89ae-411370b5cc2e.png)

**Comment by guillermomartinez** [comment]
El usuario de apache es quien se le debe dar los adecuados permisos subre la carpeta userfiles , para que suba y cree las imágenes en miniatura. Verifica en tu server

**Comment by Punksolid** [comment]
Está funcionando ahora. Efectivamente eran las rutas. 

Gracias.
