### ISSUE TITLE
auth problem 

### ISSUE THREAD

**Issue by wordpress-lab** [guillermomartinez/filemanager-laravel#18]
nice project , but when use auth middleware  it does not work . it show ....  page not found when i go to insert 
image 
![1111](https://cloud.githubusercontent.com/assets/2592229/8489794/5a8d871a-2141-11e5-9dd8-a647434b57f9.PNG)

**Comment by guillermomartinez** [comment]
Test yes working dominio.com/filemanager/show

**Comment by wordpress-lab** [comment]
nothing here dominio.com/filemanager/show

**Comment by wordpress-lab** [comment]
sir you mean it works properly.....problem is my route ?

**Comment by guillermomartinez** [comment]
What is your routes?

**Comment by wordpress-lab** [comment]
sir .....when i use http://localhost/bdfreedom/public/admin it works nice 
but when use in http://localhost/bdfreedom/public/admin/messages does not works

**Comment by guillermomartinez** [comment]
@rayhan0421 reviews https://github.com/guillermomartinez/filemanager-laravel/issues/11#issuecomment-103071664

**Comment by wordpress-lab** [comment]
sir i have no subfolder for controller, i am using latest version of file manager

**Comment by wordpress-lab** [comment]
i have tried another way....problem not solve.......route multi segment does not support. 
work with only http://localhost/bdfreedom/public/admnin not http://localhost/bdfreedom/public/admin/service or http://localhost/bdfreedom/public/admin/service/new

**Comment by guillermomartinez** [comment]
What is the value of the src of the iframe in your case?
![laravel](https://cloud.githubusercontent.com/assets/5642429/8500077/6f876826-215e-11e5-89bd-297b73d27d1d.jpg)

**Comment by wordpress-lab** [comment]
no iframe here.............
![iframe](https://cloud.githubusercontent.com/assets/2592229/8500333/f6efa20c-21bc-11e5-89f2-7b2111f7fef3.PNG)

**Comment by wordpress-lab** [comment]
here i see ........
![iframe2](https://cloud.githubusercontent.com/assets/2592229/8500359/3ebc6e30-21bd-11e5-8b7d-9d56aed9ce11.PNG)

**Comment by wordpress-lab** [comment]
so problem is file manager path ? iframe  loading problem

**Comment by guillermomartinez** [comment]
@rayhan0421 If you're right, change your absolute path 
https://github.com/guillermomartinez/filemanager-laravel/blob/master/public/tinymce/tinymce_editor.js#L33

**Comment by wordpress-lab** [comment]
it works ..........thanks you sir

**Comment by wordpress-lab** [comment]
can i config url  like that 

editor_config.selector = "textarea";
editor_config.language = "en";
tinymce.init(editor_config);

.........................
it will be very friendly

**Comment by guillermomartinez** [comment]
ya lo agrege https://github.com/guillermomartinez/filemanager-laravel/commit/257eec34cbeda0485083cdee228802854573a9c0

```
editor_config.path_absolute = "http://laravel-filemanager.rhcloud.com/";
```

**Comment by wordpress-lab** [comment]
not working...........i don't see any path_absolute into /tinymce_editor.js

**Comment by guillermomartinez** [comment]
composer update
version 2.0.3
