### ISSUE TITLE
version 2.0.3 autohide textarea

### ISSUE THREAD

**Issue by wordpress-lab** [guillermomartinez/filemanager-laravel#19]
editor_config.selector = "textarea";  auto hide. 
![iii](https://cloud.githubusercontent.com/assets/2592229/8504077/44a1d392-21ec-11e5-8d11-687bbc09167b.PNG)

**Comment by guillermomartinez** [comment]
I do not understand? , As it should be?

**Comment by wordpress-lab** [comment]
same problem like http://localhost/bdfreedom/public/admin/massages and 
http://localhost/bdfreedom/public/admin/

one works ........another does not

**Comment by guillermomartinez** [comment]
In these two routes work
http://laravel-filemanager.rhcloud.com/
http://laravel-filemanager.rhcloud.com/admin/servicios

**Comment by guillermomartinez** [comment]
You have updated the new changes?
https://github.com/guillermomartinez/filemanager-laravel/blob/master/public/tinymce/tinymce_editor.js

**Comment by wordpress-lab** [comment]
thank u sir ........working perfect ............by mistake i add ckeditor.. it was conflict problem
