### ISSUE TITLE
how enable txt file modification option

### ISSUE THREAD

**Issue by wordpress-lab** [guillermomartinez/filemanager-laravel#20]

**Comment by guillermomartinez** [comment]
https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file

**Comment by wordpress-lab** [comment]
save button don't work

**Comment by guillermomartinez** [comment]
solved update composer and update public/filemanager/scripts/filemanager.js

**Comment by wordpress-lab** [comment]
thank you its working
