### ISSUE TITLE
How to allow users to have their own folder 

### ISSUE THREAD

**Issue by wordpress-lab** [guillermomartinez/filemanager-laravel#21]
only allow user folder

**Comment by guillermomartinez** [comment]
update latest version and your controller

```
// app/Http/Controllers/FilemanagerLaravelController.php
$f = FilemanagerLaravel::Filemanager();
$f->connector_url = url('/').'/filemanager/connectors';
// create your own method according to the user autehticacion
$folderPath = 'filemanager/userfiles/user1/';
$f->setFileRoot($folderPath);
$f->run();
```

Then, open your scripts/filemanager.config.js, and make sure the fileRoot is set to '/';

https://github.com/simogeo/Filemanager/wiki/How-to-allow-users-to-have-their-own-folder-%3F

**Comment by wordpress-lab** [comment]
If i do this fileRoot is set to '/';

![fileroot](https://cloud.githubusercontent.com/assets/2592229/8528253/ce945220-2433-11e5-8a9f-ca828844b452.PNG)

![loading](https://cloud.githubusercontent.com/assets/2592229/8528220/955d5948-2433-11e5-97a5-ace13d779fbf.PNG)

in controller

![controller](https://cloud.githubusercontent.com/assets/2592229/8528283/fe967a98-2433-11e5-9c20-6ae50bc607b3.PNG)

**Comment by guillermomartinez** [comment]
detects the error using firebug firefox or chrome console
![firebug](https://cloud.githubusercontent.com/assets/5642429/8529009/c2647f2c-23dc-11e5-8502-dfd78e971caf.jpg)

**Comment by wordpress-lab** [comment]
![captureerror](https://cloud.githubusercontent.com/assets/2592229/8529561/0b119038-243d-11e5-82ef-84b8a0a550c9.PNG)

**Comment by wordpress-lab** [comment]
![errr](https://cloud.githubusercontent.com/assets/2592229/8529722/3f15e126-243e-11e5-9952-40d547d7dd24.PNG)

**Comment by guillermomartinez** [comment]
on the html tab, the server's response appears

**Comment by wordpress-lab** [comment]
![html](https://cloud.githubusercontent.com/assets/2592229/8529917/bbc462dc-243f-11e5-9570-99053d21b2cc.PNG)

**Comment by guillermomartinez** [comment]
example
![sin-titulo-1](https://cloud.githubusercontent.com/assets/5642429/8530127/b028d094-23e4-11e5-8e37-6266e3286cca.jpg)

**Comment by wordpress-lab** [comment]
![wwww](https://cloud.githubusercontent.com/assets/2592229/8530246/a664dd70-2441-11e5-814b-668158612037.PNG)

**Comment by wordpress-lab** [comment]
just 2 error

**Comment by wordpress-lab** [comment]
I think problem with controller

**Comment by wordpress-lab** [comment]
but if fileRoot set false .............its working with root path

**Comment by wordpress-lab** [comment]
![arra](https://cloud.githubusercontent.com/assets/2592229/8530363/689e7540-2442-11e5-9617-e0b00ba45992.PNG)

**Comment by wordpress-lab** [comment]
![wwwww](https://cloud.githubusercontent.com/assets/2592229/8530472/0858b8e8-2443-11e5-90b7-b6a2f03d3cb7.PNG)

**Comment by guillermomartinez** [comment]
use " not '
"fileRoot": "/",

**Comment by wordpress-lab** [comment]
![recur](https://cloud.githubusercontent.com/assets/2592229/8530665/15d92f56-2444-11e5-9471-bd8b9e9e0f51.PNG)

**Comment by wordpress-lab** [comment]
![doesnot](https://cloud.githubusercontent.com/assets/2592229/8530741/9544b8aa-2444-11e5-8209-2483252a1841.PNG)

**Comment by wordpress-lab** [comment]
![header](https://cloud.githubusercontent.com/assets/2592229/8530845/6283e926-2445-11e5-98bc-de9ab6d3c583.PNG)

**Comment by guillermomartinez** [comment]
```
// $_SERVER['DOCUMENT_ROOT']/FOLDER_SEPARATION/filemanager/userfiles/user1/;
$folderPath = 'FOLDER_SEPARATION/filemanager/userfiles/user1/';
$f->setFileRoot($folderPath);
```

**Comment by wordpress-lab** [comment]
in controller ?

**Comment by guillermomartinez** [comment]
yes

**Comment by wordpress-lab** [comment]
FOLDER_SEPARATION is function ?

**Comment by wordpress-lab** [comment]
i am using this 

$f = FilemanagerLaravel::Filemanager();
        $f->connector_url = url('/').'/filemanager/connectors';
// create your own method according to the user autehticacion
        $folderPath = 'FOLDER_SEPARATION/filemanager/userfiles/user1/';
        $f->setFileRoot($folderPath);
        $f->run();

**Comment by wordpress-lab** [comment]
confused with 'FOLDER_SEPARATION

**Comment by wordpress-lab** [comment]
![ok88](https://cloud.githubusercontent.com/assets/2592229/8531253/d2c46bdc-2447-11e5-8b6c-938becad7d70.PNG)

**Comment by wordpress-lab** [comment]
![ok95](https://cloud.githubusercontent.com/assets/2592229/8531301/2cab10c4-2448-11e5-977d-8de2bdeaf15d.PNG)

**Comment by guillermomartinez** [comment]
FOLDER_SEPARATION not function 
$folderPath = 'bdfreedom/public/filemanager/userfiles/';

**Comment by wordpress-lab** [comment]
if use this working .........$folderPath = 'bdfreedom/public/filemanager/userfiles/';

**Comment by wordpress-lab** [comment]
thank u

**Comment by wordpress-lab** [comment]
it is not flexible .$folderPath = 'bdfreedom/public/filemanager/userfiles/';

**Comment by wordpress-lab** [comment]
bdfreedom/public

**Comment by guillermomartinez** [comment]
I recommend you use a virtual host and not using localhost

**Comment by wordpress-lab** [comment]
ok thank you
