### ISSUE TITLE
 failed to open stream: Invalid argument

### ISSUE THREAD

**Issue by kingalu14** [guillermomartinez/filemanager-laravel#22]
when am trying to install your package i got this error 
- Installing pqb/filemanager-laravel (2.0.6)
  Downloading: 100%
  
  [ErrorException]
  ZipArchive::extractTo(C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\cpanel/vendor/composer/f30cd603/guillermomartinez-filemanager-laravel-a44b229\src\Pqb\Fil
  emanagerLaravel\inc\vendor\wideimage\doc\Internal-Operations/WideImage_Operation_CopyChannelsTrueColor.html): failed to open stream: Invalid argument

**Comment by guillermomartinez** [comment]
I see no problem, but if your looking in google.
Check https://github.com/composer/composer/issues/2824
