### ISSUE TITLE
Failed upload large image size : Error uploading file

### ISSUE THREAD

**Issue by firmanhcf** [guillermomartinez/filemanager-laravel#24]
Hi,
I tried to upload 7MB file, but it gives me "Error uploading file" error. Upload limit size of my server is 16MB. What should I do?

**Comment by guillermomartinez** [comment]
Check your settings with `<?php phpinfo ()?>`  in your server.
changes in your php.ini file:

```
upload_max_filesize = 40M
post_max_size = 40M
max_input_time = 300
max_execution_time = 300
```

reviews:
http://stackoverflow.com/questions/2184513/php-change-the-maximum-upload-file-size
