### ISSUE TITLE
Funciona en laravel 5.1

### ISSUE THREAD

**Issue by luchiniii** [guillermomartinez/filemanager-laravel#25]
hola estoy intentando hacer funcionar este paquete en laravel 5.1
pero el comando 

<strong>php artisan vendor:publish</strong>

Me arroja esto

<strong>Publishing complete for tag []!</strong>

y pareciera que no hace nada

**Comment by guillermomartinez** [comment]
Lo que hace el comando

```
php artisan vendor:publish
```

Es copiar unas carpetas, puedes verlo [aquí](https://github.com/guillermomartinez/filemanager-laravel/blob/master/src/Pqb/FilemanagerLaravel/FilemanagerLaravelServiceProvider.php#L39)

puedes hacerlo manualmente sino funciona el comando.

**Comment by luchiniii** [comment]
Hola 
Muchas gracias por tu pronta respuesta, ya encontré cual es el problema, al poner el paquete en el composer.json, y hacer el composer update no está descargando las carpetas apropiadamente, así que tuve que descargarlas y copiarlas manualmente.
