### ISSUE TITLE
Absolute / relative Path

### ISSUE THREAD

**Issue by BenaddiRar** [guillermomartinez/filemanager-laravel#26]
Hy ! 

how can we tell tinymc to not use relative Path :

<img width="675" alt="screen shot 2015-12-21 at 10 12 55" src="https://cloud.githubusercontent.com/assets/4574674/11928497/fa25649e-a7cb-11e5-8278-968d5fa0fac7.png">

I want Absolute Path because i Have Front/Back Application.

thQs / Merci

**Comment by guillermomartinez** [comment]
Add to file public/tinymce/tinymce_editor.js

```
relative_urls : false,
remove_script_host : false,
convert_urls : true,
```

**Comment by BenaddiRar** [comment]
:+1: & :100:
