### ISSUE TITLE
filemanger not working after remove public from url

### ISSUE THREAD

**Issue by haruncpi** [guillermomartinez/filemanager-laravel#27]
I have removed public from url by moving the **index.php** and **.htaccess** file from public directory and changing the two line in **index.php**

```
require __DIR__.'/bootstrap/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
```

now it is live in **http://localhost:141/CMS-laravel/admin**

The problem is when i click on filebrowse button it shows error in console panel and can't load all functionality.

**FilemanagerLaravelController:**

```
    public function getConnectors()
    {
        $f = FilemanagerLaravel::Filemanager();
        $this->connector_url = url('/') . '/admin/filemanager/connectors';
        $f->run();
    }
    public function postConnectors()
    {
        $f = FilemanagerLaravel::Filemanager();
        $f->connector_url = url('/') . '/admin/filemanager/connectors';
        $f->run();
    }
```

**Screenshot of problem**
![problem_filemanager](https://cloud.githubusercontent.com/assets/11594794/11973376/809e1454-a983-11e5-82f2-91c3d81a600f.jpg)

**Comment by guillermomartinez** [comment]
To rule out errors I recommend using virtual host
http://desarrollowebtutorial.com/crear-host-virtual-en-wampserver/

**Comment by haruncpi** [comment]
I have made several application and host those in share hosting by removing public from url this way,i think this method followed by most of developer. Is it possible to configure this pakage in my way? Please help me and other who are interested to integrate this pakage with my condition. I hope I'll get my solution.

**Comment by guillermomartinez** [comment]
filemanager folder must be in 

```
CMS-laravel/filemanager
```

**Comment by haruncpi** [comment]
Thanks for your response.Isn't it possible by keeping filemanager folder in current place? I mean in public folder.
