### ISSUE TITLE
On laravel 5.2.6

### ISSUE THREAD

**Issue by kotakorange** [guillermomartinez/filemanager-laravel#28]
I can't install it on Laravel 5.2.6

**Comment by thanhnguyenminh** [comment]
I think it support Laravel 5.1.x only

**Comment by ghost** [comment]
Could you please upgrade to support Laravel 5.2.*? @guillermomartinez 
Thank you very much!

**Comment by cmarfil** [comment]
+1 :)

**Comment by guillermomartinez** [comment]
update to version 2.0.7
