### ISSUE TITLE
Image uploaded but the thumbs not be displayed 

### ISSUE THREAD

**Issue by BenaddiRar** [guillermomartinez/filemanager-laravel#29]
Image uploaded but the thumbs not be displayed.

on my local development with XAMPP there's no problem but on my shared hosting I have this issue  :

(I have testes chmod 777 but nothing change.)

<img width="1144" alt="screen shot 2016-01-12 at 15 35 00" src="https://cloud.githubusercontent.com/assets/4574674/12267885/26984fb4-b942-11e5-95c0-2a3b5303bfe7.png">

**Comment by guillermomartinez** [comment]
Debug to find fault

https://cloud.githubusercontent.com/assets/2592229/8530665/15d92f56-2444-11e5-9471-bd8b9e9e0f51.PNG
