### ISSUE TITLE
Laravel 5 support [RESOLVED]

### ISSUE THREAD

**Issue by jmas** [guillermomartinez/filemanager-laravel#3]
Please add Laravel 5 support.

**Comment by guillermomartinez** [comment]
He realizado unos cambios 9deba8f32365874adfff3ffe7b8546eff36ef8ce pero este error no puedo resolverlo:

> ReflectionException in ControllerInspector.php line 28: 
> Class App\Http\Controllers\FilemanagerLaravelController does not exist

Alguna idea como resolverlo?

**Comment by guillermomartinez** [comment]
Ya lo he solucionado, con la versión 2.0

**Comment by jmas** [comment]
Hello, installed like a charm. Worked on Laravel 5.
Thank you!
