### ISSUE TITLE
Cambiar el lenguaje 

### ISSUE THREAD

**Issue by adw-cr** [guillermomartinez/filemanager-laravel#31]
Hola, como puedo cambiar el idioma de los msjs de respuesta.
Gracias

**Comment by guillermomartinez** [comment]
verifica que carge el archivo de idioma cuando cambias en el archivo scripts/filemanager.config.js
`"culture": "en",﻿`

![debug](https://cloud.githubusercontent.com/assets/5642429/13205522/e11a8a0c-d8b7-11e5-8d6c-290b01eeb2aa.jpg)
