### ISSUE TITLE
No se puede borrar una carpeta

### ISSUE THREAD

**Issue by mochetts** [guillermomartinez/filemanager-laravel#32]
exception 'ErrorException' with message 'Undefined index: extension' in /home/mmo/workspace/php/barny/vendor/pqb/filemanager-laravel/src/Pqb/FilemanagerLaravel/Filemanager.php:848

**Comment by guillermomartinez** [comment]
Solved , composer update

**Comment by didierchivas** [comment]
Hola @guillermomartinez que tal, y para laravel 4 no hay una solucion? o hay que hacerlo a manualmente?
