### ISSUE TITLE
Failed sanitize file

### ISSUE THREAD

**Issue by eaveryanau** [guillermomartinez/filemanager-laravel#39]
src/Pqb/FilemanagerLaravel/Filemanager.php - `cleanString()` method (line 841) - change variable `$clean ` (`$clean` not used in this section) to `$string`.
Now I getting error when upload file somename%С3.jpg
If I upload file "somename%С3.jpg" (use any %XX  escape chain) then i getting error.
[https://github.com/guillermomartinez/filemanager-laravel/blob/master/src/Pqb/FilemanagerLaravel/Filemanager.php#L811](url)

**Comment by guillermomartinez** [comment]
Update to 2.0.11
