### ISSUE TITLE
Make project english

### ISSUE THREAD

**Issue by simplenotezy** [guillermomartinez/filemanager-laravel#7]
Great project! Just what I need. Would it be possible for someone to translate the project into English?

**Comment by wordpress-lab** [comment]
editor_config.selector = "textarea";
editor_config.language = "en";

tinymce.init(editor_config);

**Comment by simplenotezy** [comment]
I mean the Github project

**Comment by guillermomartinez** [comment]
@canfiax if someone wants to help, would be appreciated
